name: Self-Hosted Runner Workflow

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-on-self-hosted:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Runner Info
        run: uname -a

      - name: Run a Sample Script
        run: echo "Hello from Self-Hosted Runner!"
